{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.684.0 (23.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\",\"DaxQueryView_Desktop\"]"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dCalendario-pwq\",\"dProduto\",\"dVendedor\",\"dCliente\",\"fVendas\",\"fMetas\",\"Medidas\",\"Geografia\",\"RegioesBrasil\",\"Meta_2022\",\"ClientesVendedores\",\"Supervisor\",\"CategoriaProduto\",\"fx_dias_uteis_mes\",\"Meta_2023\",\"ItensVendas\",\"Vendas\",\"fx_dias_uteis_trimestre\",\"Foto Produto\",\"Foto Vendedor\",\"vendedor ok\",\"clientes ok\",\"clienteVendedor ok\",\"Vendas (2) ok\",\"Supervisor (2) ok\",\"RegioesBrasil (2) ok\",\"Produto ok\",\"ItensVendas (2) ok\",\"Geografia (2) ok\",\"CategoriaProduto (2) ok\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Geografia",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/Geografia.csv\"),[Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "61b278e5-fad3-47ba-9090-3b549554b628"
      },
      {
        "name": "RegioesBrasil",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/RegioesBrasil.csv\"),[Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "1dfab383-6ab9-45af-bf3f-fbc905cd87c4"
      },
      {
        "name": "CategoriaProduto",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/CategoriaProduto.csv\"),[Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "f5aeb8d2-40b2-4619-bf89-7e2b3355334f"
      },
      {
        "name": "ClientesVendedores",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/clienteVendedor.csv\"),[Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "7644373c-1ff2-40c6-a1f2-aac8c17242c7"
      },
      {
        "name": "Supervisor",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/Supervisor.csv\"),[Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "a1a35396-51f8-418b-9d29-26f9e721fbcc"
      },
      {
        "name": "Vendas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/Vendas.csv\"),[Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"id\", Int64.Type}, {\"data\", type date}, {\"nfe\", type text}, {\"cliente_id\", Int64.Type}, {\"nf_desconto\", type number}, {\"valor_bruto\", Int64.Type}, {\"valor_venda\", type number}})",
          "in",
          "    #\"Tipo Alterado\""
        ],
        "kind": "m",
        "lineageTag": "f5f61656-64d0-4af7-9a74-00f6cada93a6"
      },
      {
        "name": "fx_dias_uteis_mes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(ano,mes) =>",
          "",
          "let",
          "    //ano = 2022,",
          "    //mes = 1, ",
          "    Fonte = #\"dCalendario-pwq\",",
          "    #\"Linhas Filtradas\" = Table.SelectRows(Fonte, each ([DiaSemana] <> 0 and [DiaSemana] <> 6)),",
          "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Linhas Filtradas\",{ \"Data\", \"Ano\", \"MesNum\"}),",
          "    tabela_filtrada = Table.SelectRows(#\"Outras Colunas Removidas\", each ([Ano] = ano) and ([MesNum] = mes)),",
          "    #\"Personalização Adicionada\" = Table.AddColumn(tabela_filtrada, \"qtde_dias_uteis\", each Table.RowCount(tabela_filtrada))",
          "in",
          "    #\"Personalização Adicionada\""
        ],
        "kind": "m",
        "lineageTag": "03028b03-6f2b-49a4-9469-b92c65de9081",
        "queryGroup": "Dimensões"
      },
      {
        "name": "Meta_2023",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\Ricardo\\OneDrive\\Documentos\\Dev\\Xperiun\\semana-data-expert-dados\\Meta_2023.xlsx\"), null, true),",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(Fonte,{\"Item\", \"Kind\", \"Hidden\"}),",
          "    #\"Data Expandido\" = Table.ExpandTableColumn(#\"Colunas Removidas\", \"Data\", {\"Column1\", \"Column2\", \"Column3\", \"Column4\", \"Column5\", \"Column6\", \"Column7\"}, {\"Data.Column1\", \"Data.Column2\", \"Data.Column3\", \"Data.Column4\", \"Data.Column5\", \"Data.Column6\", \"Data.Column7\"}),",
          "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Data Expandido\", each ([Data.Column2] <> null)),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Linhas Filtradas\", [PromoteAllScalars=true]),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"1 - Victor Castro\", type text}, {\"Categoria Produto\", type text}, {\"Previsão Vendas\", type any}, {\"1\", type number}, {\"2\", type number}, {\"3\", type number}, {\"4\", type number}, {\"Total\", type any}}),",
          "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Tipo Alterado\", each ([Previsão Vendas] <> \"Previsão Vendas\")),",
          "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Linhas Filtradas1\",{\"Total\"}),",
          "    #\"Colunas Não Dinâmicas\" = Table.UnpivotOtherColumns(#\"Colunas Removidas1\", {\"1 - Victor Castro\", \"Categoria Produto\", \"Previsão Vendas\"}, \"Atributo\", \"Valor\"),",
          "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Não Dinâmicas\",{{\"Atributo\", \"trimeste\"}, {\"Valor\", \"fator\"}, {\"1 - Victor Castro\", \"gerente_id\"}, {\"Categoria Produto\", \"Categoria_id\"}}),",
          "    #\"Multiplicação Inserida\" = Table.AddColumn(#\"Colunas Renomeadas\", \"valor_trimestre\", each [Previsão Vendas] * [fator], type number),",
          "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Multiplicação Inserida\",{\"Previsão Vendas\", \"fator\"}),",
          "    #\"Texto Extraído Antes do Delimitador\" = Table.TransformColumns(#\"Colunas Removidas2\", {{\"gerente_id\", each Text.BeforeDelimiter(_, \" \"), type text}, {\"Categoria_id\", each Text.BeforeDelimiter(_, \" \"), type text}}),",
          "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Texto Extraído Antes do Delimitador\",{{\"gerente_id\", Int64.Type}, {\"Categoria_id\", Int64.Type}, {\"trimeste\", Int64.Type}, {\"valor_trimestre\", Int64.Type}}),",
          "    #\"Função Personalizada Invocada\" = Table.AddColumn(#\"Tipo Alterado1\", \"qtde_dias_uteis\", each fx_dias_uteis_trimestre(2023, [trimeste])),",
          "    #\"qtde_dias_uteis Expandido\" = Table.ExpandTableColumn(#\"Função Personalizada Invocada\", \"qtde_dias_uteis\", {\"Data\", \"qtde_dias_uteis\"}, {\"qtde_dias_uteis.Data\", \"qtde_dias_uteis.qtde_dias_uteis\"}),",
          "    #\"Personalização Adicionada\" = Table.AddColumn(#\"qtde_dias_uteis Expandido\", \"meta_diaria\", each [valor_trimestre]/[qtde_dias_uteis.qtde_dias_uteis]),",
          "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"qtde_dias_uteis.Data\", type date}, {\"meta_diaria\", type number}}),",
          "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Tipo Alterado2\",{{\"qtde_dias_uteis.Data\", \"Data\"}, {\"meta_diaria\", \"valor\"}}),",
          "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Colunas Renomeadas1\",{\"gerente_id\", \"Categoria_id\", \"Data\", \"valor\"}),",
          "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Outras Colunas Removidas\",{{\"Categoria_id\", \"categoria_id\"}})",
          "in",
          "    #\"Colunas Renomeadas2\""
        ],
        "kind": "m",
        "lineageTag": "10e67b96-0d3f-4b76-9c75-eb3691fbd002"
      },
      {
        "name": "fx_dias_uteis_trimestre",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(ano,Trimestre) =>",
          "",
          "let",
          "    //ano = 2022,",
          "    //mes = 1, ",
          "    Fonte = #\"dCalendario-pwq\",",
          "    #\"Linhas Filtradas\" = Table.SelectRows(Fonte, each ([DiaSemana] <> 0 and [DiaSemana] <> 6)),",
          "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Linhas Filtradas\",{ \"Data\", \"Ano\", \"Trimestre\"}),",
          "    tabela_filtrada = Table.SelectRows(#\"Outras Colunas Removidas\", each ([Ano] = ano) and ([Trimestre] = Trimestre)),",
          "    #\"Personalização Adicionada\" = Table.AddColumn(tabela_filtrada, \"qtde_dias_uteis\", each Table.RowCount(tabela_filtrada))",
          "in",
          "    #\"Personalização Adicionada\""
        ],
        "kind": "m",
        "lineageTag": "3d453869-06dd-495a-912b-fd84cbdc73ee",
        "queryGroup": "Dimensões"
      },
      {
        "name": "Meta_2022",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\Ricardo\\OneDrive\\Documentos\\Dev\\Xperiun\\semana-data-expert-dados\\Meta_2022.csv\"),[Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Mês\", type date}, {\"gerente_id\", Int64.Type}, {\"categoria_id\", Int64.Type}, {\"$ Meta\", Int64.Type}}),",
          "    #\"Ano Inserido\" = Table.AddColumn(#\"Tipo Alterado\", \"Ano\", each Date.Year([Mês]), Int64.Type),",
          "    #\"Mês Inserido\" = Table.AddColumn(#\"Ano Inserido\", \"MesNum\", each Date.Month([Mês]), Int64.Type),",
          "    #\"Função Personalizada Invocada\" = Table.AddColumn(#\"Mês Inserido\", \"dias_uteis\", each fx_dias_uteis_mes([Ano], [MesNum])),",
          "    #\"dias_uteis Expandido\" = Table.ExpandTableColumn(#\"Função Personalizada Invocada\", \"dias_uteis\", {\"Data\", \"qtde_dias_uteis\"}, {\"dias_uteis.Data\", \"dias_uteis.qtde_dias_uteis\"}),",
          "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"dias_uteis Expandido\",{{\"dias_uteis.qtde_dias_uteis\", \"qtde_dias_uteis\"}, {\"dias_uteis.Data\", \"Data\"}}),",
          "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas\", \"meta_diaria\", each [#\"$ Meta\"]/[qtde_dias_uteis]),",
          "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Personalização Adicionada\",{\"Data\", \"meta_diaria\", \"gerente_id\", \"categoria_id\", \"qtde_dias_uteis\"}),",
          "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Outras Colunas Removidas\",{{\"Data\", type date}, {\"meta_diaria\", type number}, {\"qtde_dias_uteis\", Int64.Type}}),",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado1\",{\"qtde_dias_uteis\"}),",
          "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"meta_diaria\", \"valor\"}})",
          "in",
          "    #\"Colunas Renomeadas1\""
        ],
        "kind": "m",
        "lineageTag": "2d99fe7f-a73b-4cf8-bf14-b1cc75e7ef6e"
      },
      {
        "name": "Foto Produto",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\Ricardo\\OneDrive\\Documentos\\Dev\\Xperiun\\semana-data-expert-dados\\PinskiDatabase_Fotos.xlsx\"), null, true),",
          "    #\"Foto Produto_Sheet\" = Fonte{[Item=\"Foto Produto\",Kind=\"Sheet\"]}[Data],",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Foto Produto_Sheet\",{{\"Column1\", type text}, {\"Column2\", type text}}),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Tipo Alterado\", [PromoteAllScalars=true]),",
          "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Produto\", type text}, {\"URL\", type text}})",
          "in",
          "    #\"Tipo Alterado1\""
        ],
        "kind": "m",
        "lineageTag": "b5ae8185-e8ae-4543-80e6-38bb5a909554"
      },
      {
        "name": "Foto Vendedor",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\Ricardo\\OneDrive\\Documentos\\Dev\\Xperiun\\semana-data-expert-dados\\PinskiDatabase_Fotos.xlsx\"), null, true),",
          "    #\"Foto Vendedor_Sheet\" = Fonte{[Item=\"Foto Vendedor\",Kind=\"Sheet\"]}[Data],",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Foto Vendedor_Sheet\", [PromoteAllScalars=true]),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"id_vendedor\", Int64.Type}, {\"URL\", type text}})",
          "in",
          "    #\"Tipo Alterado\""
        ],
        "kind": "m",
        "lineageTag": "99c3f269-3a4c-4b92-8344-eacb8c0a6e94"
      },
      {
        "name": "vendedor ok",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/vendedor.csv\"),[Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "077ff3ba-39b8-46b1-8d32-126b725229ee",
        "queryGroup": "Origin GitHub"
      },
      {
        "name": "clientes ok",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/clientes.csv\"),[Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "6d9c53c7-b1de-425e-9a38-04d7171deb2c",
        "queryGroup": "Origin GitHub"
      },
      {
        "name": "clienteVendedor ok",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/clienteVendedor.csv\"),[Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "54bd3ab0-cbf1-439e-94d0-604acc38df9f",
        "queryGroup": "Origin GitHub"
      },
      {
        "name": "Vendas (2) ok",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/Vendas.csv\"),[Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "cb75dc2a-fdbd-43cf-a960-5aa6cb0abb2d",
        "queryGroup": "Origin GitHub"
      },
      {
        "name": "Supervisor (2) ok",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/Supervisor.csv\"),[Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "ccf778b9-16bd-453f-a97f-13aabd8da00d",
        "queryGroup": "Origin GitHub"
      },
      {
        "name": "RegioesBrasil (2) ok",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/RegioesBrasil.csv\"),[Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None])",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "0572db87-c676-4a7e-8373-2775012989a5",
        "queryGroup": "Origin GitHub"
      },
      {
        "name": "Produto ok",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/Produto.csv\"),[Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "b0361fcf-e99d-477a-9c87-5a26a3ef2dfa",
        "queryGroup": "Origin GitHub"
      },
      {
        "name": "ItensVendas (2) ok",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/ItensVendas.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "bf194947-fb28-445c-8b0a-cf0e1bfd8922",
        "queryGroup": "Origin GitHub"
      },
      {
        "name": "Geografia (2) ok",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/Geografia.csv\"),[Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"id\", Int64.Type}})",
          "in",
          "    #\"Tipo Alterado\""
        ],
        "kind": "m",
        "lineageTag": "a5cc02bb-6cd7-4a7e-8a09-95b1e4d5b05d",
        "queryGroup": "Origin GitHub"
      },
      {
        "name": "CategoriaProduto (2) ok",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/CategoriaProduto.csv\"),[Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "42abf33e-166d-4b6b-8995-1f169faeb541",
        "queryGroup": "Origin GitHub"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Dimensões"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Fatos"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "description": "fontes de dados github ou web",
        "folder": "Origin GitHub"
      }
    ],
    "relationships": [
      {
        "name": "78e888df-6c8b-4501-80cb-c6eeefa24ff8",
        "fromColumn": "id",
        "fromTable": "fVendas",
        "toColumn": "id",
        "toTable": "dCliente"
      },
      {
        "name": "2cfb7bde-f4b9-4079-9909-19db22817e9f",
        "fromColumn": "vendedor_id",
        "fromTable": "fVendas",
        "toColumn": "id_vendedor",
        "toTable": "dVendedor"
      },
      {
        "name": "26c7fce7-57ca-47a1-982c-f13fdd0ac956",
        "fromColumn": "data",
        "fromTable": "fVendas",
        "toColumn": "Data",
        "toTable": "dCalendario-pwq"
      },
      {
        "name": "6996cba6-04e7-4b4e-b707-77ce89d4ab2d",
        "fromColumn": "Data",
        "fromTable": "fMetas",
        "toColumn": "Data",
        "toTable": "dCalendario-pwq"
      },
      {
        "name": "04b273f4-46ec-4700-9a9a-1bc50c372b4d",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "gerente_id",
        "fromTable": "dVendedor",
        "isActive": false,
        "toColumn": "gerente_id",
        "toTable": "dgerente"
      },
      {
        "name": "27bf6c51-d096-43ee-ac85-a35b43c7b801",
        "fromColumn": "gerente_id",
        "fromTable": "fMetas",
        "isActive": false,
        "toColumn": "gerente_id",
        "toTable": "dgerente"
      },
      {
        "name": "f404e11c-b8e3-4301-b749-3e3d2d9fd655",
        "fromColumn": "gerente_id",
        "fromTable": "fMetas",
        "toCardinality": "many",
        "toColumn": "gerente_id",
        "toTable": "dVendedor"
      },
      {
        "name": "cf8ca12e-6544-43b4-bf45-9b4dbda81c52",
        "fromColumn": "categoria_id",
        "fromTable": "fMetas",
        "toCardinality": "many",
        "toColumn": "categoria_id",
        "toTable": "dProduto"
      },
      {
        "name": "53681483-9d1d-4f5c-8994-7a82a28f310f",
        "fromColumn": "produto_id",
        "fromTable": "fVendas",
        "toColumn": "id",
        "toTable": "dProduto"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DateTableTemplate_299482dd-c6b7-4947-8edd-83e4dfe720fa",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0120af5a-8cf1-4eaf-bf43-3b08f60aa09c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "a4052475-3afb-4d31-be0e-110e5d3af25f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9c273a67-2af5-46b7-8e9e-1b621b96c1d5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "aa9fbe89-46c9-487d-8c5f-8d10cdd366cc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c6292b6e-0559-4bc3-a68a-9d960ebd7a73",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3e9556ba-7864-40a0-b208-dce15c711238",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "83fd861b-a3cb-482e-89f7-bb7219108c7b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "ff650ebb-e619-4685-903f-c8eb0142b553",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "7f0ce33e-969a-476d-ae0a-b9434b5c6d58",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "bb658962-b5f8-4533-b0b6-675dfd22a7e4",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "5527a287-0970-47b5-ac6c-cadc12967cad",
                "ordinal": 3
              }
            ],
            "lineageTag": "86e148df-ec9f-4513-95b0-bee17ec197ef"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "914daa74-5cd5-48e4-a4ee-8b4a95bfbb42",
        "partitions": [
          {
            "name": "DateTableTemplate_299482dd-c6b7-4947-8edd-83e4dfe720fa",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dCalendario-pwq",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "d92a1df8-5c31-4f2a-a91a-af76ed3c1083",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e6d74cc1-7925-4140-9a65-1de355cc5ec4",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "NomeMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02050231-f154-4477-9b33-bc3f9ed5e357",
            "sourceColumn": "NomeMes",
            "summarizeBy": "none"
          },
          {
            "name": "MesAbre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "725d5d89-b86e-4a43-bcba-b05862c768e0",
            "sortByColumn": "MesNum",
            "sourceColumn": "MesAbre",
            "summarizeBy": "none"
          },
          {
            "name": "MesAno",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31461997-d844-4819-aba2-2cd7a2e035d8",
            "sourceColumn": "MesAno",
            "summarizeBy": "none"
          },
          {
            "name": "MesNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "02ce559b-e29e-4ed7-9505-62bf46e07a93",
            "sourceColumn": "MesNum",
            "summarizeBy": "sum"
          },
          {
            "name": "AnoMesINT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "19217d1c-34f3-436e-8208-ff6c08304965",
            "sourceColumn": "AnoMesINT",
            "summarizeBy": "sum"
          },
          {
            "name": "InicioMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5bf1aa0f-93c1-4d23-9a7b-16a5ab6e08e3",
            "sourceColumn": "InicioMes",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6619efd9-1031-4070-873c-6420e2665670",
            "sourceColumn": "Trimestre",
            "summarizeBy": "sum"
          },
          {
            "name": "TrimestreAbreviado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87d788c6-d84b-40f8-8717-192472e7e354",
            "sourceColumn": "TrimestreAbreviado",
            "summarizeBy": "none"
          },
          {
            "name": "Bimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cac0b02e-0fac-49e1-88f3-83cf50d838b2",
            "sourceColumn": "Bimestre",
            "summarizeBy": "none"
          },
          {
            "name": "Semestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1a9a475-1fef-433d-aeed-4aa7009755e5",
            "sourceColumn": "Semestre",
            "summarizeBy": "none"
          },
          {
            "name": "Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b7bc83fc-3b6f-48cc-925e-7fec0975eb23",
            "sourceColumn": "Semana",
            "summarizeBy": "sum"
          },
          {
            "name": "DiaSemana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "afe770ed-050c-4237-8092-0f56cee7019f",
            "sourceColumn": "DiaSemana",
            "summarizeBy": "sum"
          },
          {
            "name": "NomeDia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "539c7166-37a6-413a-bd0f-d6884ba24517",
            "sourceColumn": "NomeDia",
            "summarizeBy": "none"
          },
          {
            "name": "Ja_passo?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": [
              "",
              "IF( ",
              "    'dCalendario-pwq'[Data] <+ MAX(fVendas[data]),",
              "    TRUE()",
              ")",
              ""
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "lineageTag": "5c1ff835-03c0-4318-a02b-3dd469b56d35",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "37fb7096-913e-46ee-9a3a-32b0dbe668d2",
        "partitions": [
          {
            "name": "dCalendario-pwq",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "",
                "//Alterar somente a Tabela e a coluna de datas",
                "/* A Tabela é onde possui uma coluna Data que deseja usar em seus cálculos ou visuais. ",
                "Exemplo. Tabela fVendas que possui a coluna Data Pedido Ficaria List.Min (fVendas[Data Pedido]).",
                "Se Possuir mais de uma coluna ficaria List.Min (fVendas[Data Pedido] & fVendas[Data Vencimento]).",
                "*/",
                "",
                "    MenorData = #date(2021,01,01),",
                "    MaiorData = #date(2023,12,31),",
                "\t",
                "//Não alterar daqui pra baixo\t",
                "\t",
                "    DataInicio = Date.StartOfYear(MenorData),",
                "    DataFim = Date.EndOfYear(MaiorData),",
                "    Dias = Duration.Days(DataFim- DataInicio) +1,",
                "    ListarDatas = List.Dates(DataInicio, Dias, #duration(1,0,0,0)),",
                "    Tabela = #table(",
                "        type table[",
                "            Data = date,",
                "            Ano = Int64.Type,",
                "            NomeMes = text,",
                "            MesAbre = text,",
                "            MesAno = text,",
                "            MesNum = number,",
                "            AnoMesINT = number,",
                "            InicioMes = date,",
                "            Trimestre = Int64.Type,",
                "            TrimestreAbreviado = text,",
                "            Bimestre = text,",
                "            Semestre = text,",
                "            Semana = Int64.Type,",
                "            DiaSemana = Int64.Type,",
                "            NomeDia = text ",
                "        ],",
                "        List.Transform(",
                "            ListarDatas,",
                "            each {",
                "                _,",
                "                Date.Year(_),",
                "                Text.Proper( Date.MonthName(_)),",
                "                Text.Proper(Text.Start(Date.MonthName(_), 3)),",
                "                Text.Proper(Text.Start(Date.MonthName(_), 3)) & \"-\" & Text.End(Text.From(Date.Year(_)), 2),",
                "                Date.Month(_),",
                "                Date.Year(_) * 100 + Date.Month(_),",
                "                Date.StartOfMonth(_),",
                "                Date.QuarterOfYear(_),",
                "                Text.From(Date.QuarterOfYear(_)) & \"º Trim \",",
                "                Text.From( Number.RoundUp( Date.Month(_)/2,0)) & \"º Bim\",",
                "                Text.From( Number.RoundUp( Date.Month(_)/6,0)) & \"º Sem\",",
                "                Date.WeekOfMonth(_),",
                "                Date.DayOfWeek(_),",
                "                Date.DayOfWeekName(_)",
                "",
                "            }",
                "",
                "        )",
                "    )",
                "in",
                "    Tabela"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCliente",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75e85d26-e3df-48fd-8bb9-78a4bdabfd64",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "geografia_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e12a9d37-0247-4a84-afb3-b2014abc1407",
            "sourceColumn": "geografia_id",
            "summarizeBy": "none"
          },
          {
            "name": "descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b951c5d1-2666-46c6-8629-a1a0d6ec1548",
            "sourceColumn": "descricao",
            "summarizeBy": "none"
          },
          {
            "name": "Regiao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9098fea6-3698-4547-80f6-357d4046c33c",
            "sourceColumn": "Regiao",
            "summarizeBy": "none"
          },
          {
            "name": "cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d8df122-e33e-4ce0-9132-fd95c2f5b4ce",
            "sourceColumn": "cidade",
            "summarizeBy": "none"
          },
          {
            "name": "uf",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0c6c20c-6404-46be-8874-f1b18529cd5d",
            "sourceColumn": "uf",
            "summarizeBy": "none"
          },
          {
            "name": "estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74b52784-601b-4bc9-9990-11f80b39d99d",
            "sourceColumn": "estado",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "08bb9831-8718-4bca-ab76-3025125b4a28",
        "partitions": [
          {
            "name": "dCliente",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/clientes.csv\"),[Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"id\", Int64.Type}, {\"geografia_id\", Int64.Type}, {\"descricao\", type text}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Tipo Alterado\", {\"geografia_id\"}, Geografia, {\"id\"}, \"Geografia\", JoinKind.LeftOuter),",
                "    #\"Geografia Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"Geografia\", {\"cidade\", \"uf\", \"estado\"}, {\"cidade\", \"uf\", \"estado\"}),",
                "    #\"Consultas Mescladas1\" = Table.NestedJoin(#\"Geografia Expandido\", {\"uf\"}, RegioesBrasil, {\"UF\"}, \"RegioesBrasil\", JoinKind.LeftOuter),",
                "    #\"RegioesBrasil Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas1\", \"RegioesBrasil\", {\"Regiao\"}, {\"RegioesBrasil.Regiao\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"RegioesBrasil Expandido\",{{\"RegioesBrasil.Regiao\", \"Regiao\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dProduto",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "88c3c4b6-c2f9-4cbe-a5a6-96564217f2e7",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "categoria_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c108cfb-c4c8-45e5-9953-cbd8589916d1",
            "sourceColumn": "categoria_id",
            "summarizeBy": "none"
          },
          {
            "name": "descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15216fe4-e290-487a-a5bb-81b3c00c1b90",
            "sourceColumn": "descricao",
            "summarizeBy": "none"
          },
          {
            "name": "tamanho",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43ebe6aa-9b23-4ca3-b6f1-399c58314d8f",
            "sourceColumn": "tamanho",
            "summarizeBy": "none"
          },
          {
            "name": "custoUnitario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1efc9214-f039-4be6-8c59-5c47de0a448d",
            "sourceColumn": "custoUnitario",
            "summarizeBy": "sum"
          },
          {
            "name": "categoria_descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b992bba-2ba5-4ead-9e7a-699b0aec7701",
            "sourceColumn": "categoria_descricao",
            "summarizeBy": "none"
          },
          {
            "name": "Foto Produto.URL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7cf2abc3-91e7-41b7-bfce-0ea955b912c0",
            "sourceColumn": "Foto Produto.URL",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4cc4619f-eab0-439b-857c-351671db0134",
        "partitions": [
          {
            "name": "dProduto",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/Produto.csv\"),[Delimiter=\",\", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"id\", Int64.Type}, {\"categoria_id\", Int64.Type}, {\"descricao\", type text}, {\"tamanho\", type text}, {\"custoUnitario\", Int64.Type}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Tipo Alterado\", {\"categoria_id\"}, CategoriaProduto, {\"id\"}, \"CategoriaProduto\", JoinKind.LeftOuter),",
                "    #\"CategoriaProduto Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"CategoriaProduto\", {\"descricao\"}, {\"CategoriaProduto.descricao\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"CategoriaProduto Expandido\",{{\"CategoriaProduto.descricao\", \"categoria_descricao\"}}),",
                "    #\"Consultas Mescladas1\" = Table.NestedJoin(#\"Colunas Renomeadas\", {\"descricao\"}, #\"Foto Produto\", {\"Produto\"}, \"Foto Produto\", JoinKind.LeftOuter),",
                "    #\"Foto Produto Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas1\", \"Foto Produto\", {\"URL\"}, {\"Foto Produto.URL\"})",
                "in",
                "    #\"Foto Produto Expandido\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dVendedor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "id_vendedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ef882968-e81b-4888-851a-d8b095252412",
            "sourceColumn": "id_vendedor",
            "summarizeBy": "none"
          },
          {
            "name": "Vendedor_descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d1c8f5e-0a37-4aba-b3e0-c0591bf5ba7e",
            "sourceColumn": "Vendedor_descricao",
            "summarizeBy": "none"
          },
          {
            "name": "supervisor_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b3275e3b-938c-432c-be99-512145b98d3f",
            "sourceColumn": "supervisor_id",
            "summarizeBy": "sum"
          },
          {
            "name": "gerente_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9bb164cc-0701-4834-a2f1-b51184863ee1",
            "sourceColumn": "gerente_id",
            "summarizeBy": "none"
          },
          {
            "name": "sup_descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fefb16e-23a8-4335-aca5-55204898b7a2",
            "sourceColumn": "sup_descricao",
            "summarizeBy": "none"
          },
          {
            "name": "gerente_descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1cf1b9c-377e-4bf0-97c5-518a2ee485b8",
            "sourceColumn": "gerente_descricao",
            "summarizeBy": "none"
          },
          {
            "name": "Foto Vendedor.URL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fe53cc0-96d5-4ed6-8fbd-bc9587ecceae",
            "sourceColumn": "Foto Vendedor.URL",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fa9d4317-c3d9-40dd-aaa7-06e6ee7036f8",
        "partitions": [
          {
            "name": "dVendedor",
            "mode": "import",
            "queryGroup": "Dimensões",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/vendedor.csv\"),[Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"id\", Int64.Type}, {\"descricao\", type text}, {\"supervisor_id\", Int64.Type}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Tipo Alterado\", {\"supervisor_id\"}, Supervisor, {\"id\"}, \"Supervisor\", JoinKind.LeftOuter),",
                "    #\"Supervisor Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"Supervisor\", {\"descricao\", \"gerente_id\", \"gerente_descricao\"}, {\"suo_descricao\", \"gerente_id\", \"gerente_descricao\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Supervisor Expandido\",{{\"descricao\", \"Vendedor_descricao\"}, {\"id\", \"id_vendedor\"}, {\"suo_descricao\", \"sup_descricao\"}}),",
                "    #\"Consultas Mescladas1\" = Table.NestedJoin(#\"Colunas Renomeadas\", {\"supervisor_id\"}, #\"Foto Vendedor\", {\"id_vendedor\"}, \"Foto Vendedor\", JoinKind.LeftOuter),",
                "    #\"Foto Vendedor Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas1\", \"Foto Vendedor\", {\"URL\"}, {\"Foto Vendedor.URL\"})",
                "in",
                "    #\"Foto Vendedor Expandido\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fVendas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3c8abf6-cd10-4862-9fd1-b6b3d5c5cb3e",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "79f458ed-5d00-4c31-afb7-9a6ef786b091",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "nfe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6bbff52a-dfa5-4bea-8274-222591b96f86",
            "sourceColumn": "nfe",
            "summarizeBy": "none"
          },
          {
            "name": "cliente_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41c7d56a-d455-45de-8b18-b867a948315e",
            "sourceColumn": "cliente_id",
            "summarizeBy": "sum"
          },
          {
            "name": "produto_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc399dd4-e599-4d2e-a70d-983eb3dd0d58",
            "sourceColumn": "produto_id",
            "summarizeBy": "none"
          },
          {
            "name": "item_quantidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd63d00b-b075-4183-92a8-1387795b30ce",
            "sourceColumn": "item_quantidade",
            "summarizeBy": "sum"
          },
          {
            "name": "valor_unitario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "09d79389-3f6e-4262-ab92-13d980259d8c",
            "sourceColumn": "valor_unitario",
            "summarizeBy": "sum"
          },
          {
            "name": "valor_desconto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1019d86-6781-4ca4-bb60-225f98687dfb",
            "sourceColumn": "valor_desconto",
            "summarizeBy": "none"
          },
          {
            "name": "vendedor_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "060c2db0-e574-4c1e-8712-127f0bc9166d",
            "sourceColumn": "vendedor_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "53f6823c-7431-49a9-b339-554463927171",
        "partitions": [
          {
            "name": "fVendas",
            "mode": "import",
            "queryGroup": "Fatos",
            "source": {
              "expression": [
                "let",
                "    Fonte = Vendas,",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(Fonte, {\"id\"}, ItensVendas, {\"vendas_id\"}, \"ItensVendas\", JoinKind.LeftOuter),",
                "    #\"ItensVendas Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"ItensVendas\", {\"id\", \"vendas_id\", \"produto_id\", \"item_quantidade\", \"valor_unitario\", \"valor_bruto\"}, {\"ItensVendas.id\", \"ItensVendas.vendas_id\", \"ItensVendas.produto_id\", \"ItensVendas.item_quantidade\", \"ItensVendas.valor_unitario\", \"ItensVendas.valor_bruto\"}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"ItensVendas Expandido\", \"valor_desconto\", each [nf_desconto] * [ItensVendas.valor_bruto] / [valor_bruto]),",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(#\"Personalização Adicionada\",{\"id\", \"data\", \"nfe\", \"cliente_id\", \"ItensVendas.produto_id\", \"ItensVendas.item_quantidade\", \"ItensVendas.valor_unitario\", \"valor_desconto\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Outras Colunas Removidas\",{{\"ItensVendas.produto_id\", \"produto_id\"}, {\"ItensVendas.item_quantidade\", \"item_quantidade\"}, {\"ItensVendas.valor_unitario\", \"valor_unitario\"}}),",
                "    #\"Consultas Mescladas1\" = Table.NestedJoin(#\"Colunas Renomeadas\", {\"cliente_id\"}, ClientesVendedores, {\"cliente_id\"}, \"ClientesVendedores\", JoinKind.LeftOuter),",
                "    #\"ClientesVendedores Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas1\", \"ClientesVendedores\", {\"vendedor_id\"}, {\"ClientesVendedores.vendedor_id\"}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"ClientesVendedores Expandido\",{{\"ClientesVendedores.vendedor_id\", \"vendedor_id\"}})",
                "in",
                "    #\"Colunas Renomeadas1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Coluna 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8b7396a0-69a1-4039-9eb6-7d59924283aa",
            "sourceColumn": "Coluna 1",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "6a07b12d-36c9-44fa-885e-9ca0b4048c8b",
        "measures": [
          {
            "name": "itens_vendidos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "expression": "SUM(fVendas[item_quantidade])",
            "formatString": "\"R$\"#,0;-\"R$\"#,0;\"R$\"#,0",
            "lineageTag": "0b9b0780-8788-4cc0-b70f-735bf0ed0d4f"
          },
          {
            "name": "preco_media_unitario",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-BR\"}"
              }
            ],
            "expression": "AVERAGE(fVendas[valor_unitario])",
            "formatString": "\"R$\"#,0.00;-\"R$\"#,0.00;\"R$\"#,0.00",
            "lineageTag": "1a441095-773d-492a-a395-aca21f6beed9"
          },
          {
            "name": "$faturamento",
            "expression": [
              "",
              "         SUMX(fVendas, fVendas[valor_unitario] * fVendas[item_quantidade] - fVendas[valor_desconto])",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "7e2d7e37-577a-40e7-9f35-c05eba845abe"
          },
          {
            "name": "quantidade_vendas",
            "expression": "DISTINCTCOUNT(fVendas[nfe])",
            "formatString": "0",
            "lineageTag": "f7ed4b07-61db-4d31-bf64-25d6c6c63085"
          },
          {
            "name": "ticket_medio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([$faturamento],[quantidade_vendas])",
            "lineageTag": "36ef61fa-c325-4b8b-a233-9ecc1918d609"
          },
          {
            "name": "$meta total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "SUM(fMetas[valor])",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "42f24c37-a95f-4688-9c4f-9144acdc27f5"
          },
          {
            "name": "fator_vendedores",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var _qtde_vendedores = COUNTROWS(dVendedor)",
              "",
              "var _vendedores = CALCULATE(",
              "    COUNTROWS(dVendedor),",
              "    ALL(dVendedor),",
              "    VALUES(dVendedor[gerente_descricao])",
              ")",
              "var _result = DIVIDE(_qtde_vendedores,_vendedores)",
              "",
              "return  _result"
            ],
            "lineageTag": "30ba73aa-14e3-46eb-980e-8b088b9e3c6b"
          },
          {
            "name": "fator_produto",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var _fatpy = CALCULATE(",
              "    [$faturamento],",
              "        PREVIOUSYEAR('dCalendario-pwq'[Data])",
              ")",
              "var _fatPyTotal = CALCULATE(",
              "    [$faturamento],",
              "    PREVIOUSYEAR('dCalendario-pwq'[Data]),",
              "    ALL(dProduto),",
              "    VALUES(dProduto[categoria_id])",
              ")",
              "var _result = DIVIDE(_fatpy,_fatPyTotal)",
              "",
              "return _result "
            ],
            "lineageTag": "87841127-6d39-433d-8652-b05144e3cd67"
          },
          {
            "name": "$meta_diluida",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SUMX(",
              "    CROSSJOIN(",
              "        VALUES(dProduto[categoria_id]),",
              "        VALUES(dVendedor[gerente_id])",
              "    ),",
              "[$meta total] * [fator_produto] * [fator_vendedores]",
              ")"
            ],
            "lineageTag": "2bbecb11-33a0-4d32-9552-09b9a30c28ef"
          },
          {
            "name": "$meta_MTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    [$meta_diluida],",
              "    DATESMTD('dCalendario-pwq'[Data])",
              ")"
            ],
            "lineageTag": "5a94957d-717b-40b2-bd1b-750b39e5ca5c"
          },
          {
            "name": "$faturamento_MTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    [$faturamento],",
              "    DATESMTD('dCalendario-pwq'[Data])",
              "",
              ")"
            ],
            "lineageTag": "c152b7ce-cc0a-4869-8fe3-97a0bb021f07"
          },
          {
            "name": "Faturamento vs Meta",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[$faturamento] - [$meta_diluida]",
            "lineageTag": "0c8edd04-cff4-49cf-9df5-52022d850775"
          },
          {
            "name": "cor_visual",
            "expression": [
              "",
              "IF(",
              "    [Faturamento vs Meta] > 0,",
              "    \"#564CFB\", // bateu a meta ",
              "    \"#FA8187\"  //Não bateu a meta",
              "",
              ")"
            ],
            "lineageTag": "adb968ce-4c09-4257-a184-659fde6abaaa"
          },
          {
            "name": "Rotulo de dados",
            "expression": [
              "",
              "var _ft = [$faturamento]",
              "var _result = ",
              "SWITCH(TRUE(),",
              "_ft > 1E6, FORMAT(_ft,\"#0,,.0 Mi\"),",
              "BLANK()",
              ")",
              "",
              "return _result",
              ""
            ],
            "lineageTag": "2113ddbf-0393-45ce-9e92-c7f632fc5129"
          },
          {
            "name": "itenm mais vendido",
            "expression": [
              "",
              "    CALCULATE(",
              "    MAXX(fVendas, RELATED(dProduto[descricao]),TRUE),",
              "    fVendas[vendedor_id]",
              "    )"
            ],
            "lineageTag": "7e49af03-4ab3-426e-b1ba-29416fa31753"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlSKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fMetas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "gerente_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8f60d3f9-0d41-46cb-84b2-4dc630a28443",
            "sourceColumn": "gerente_id",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e99cbd29-2d0b-4140-bb1d-f12156be0457",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "2c1cde69-e89d-4b09-8b3d-9926d3895885",
            "sourceColumn": "valor",
            "summarizeBy": "sum"
          },
          {
            "name": "categoria_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e158267b-2806-419e-83f3-31eb4648c484",
            "sourceColumn": "categoria_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "963688d7-835e-4d34-aecf-3b9245be7c78",
        "partitions": [
          {
            "name": "fMetas",
            "mode": "import",
            "queryGroup": "Fatos",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.Combine({Meta_2023, Meta_2022})",
                "in",
                "    Fonte"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dgerente",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4184c6c94cc64522a195d9a87074ee3f"
          }
        ],
        "columns": [
          {
            "name": "gerente_descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fbb67fe3-d36a-4b73-812f-d91f32ab836a",
            "sourceColumn": "dVendedor[gerente_descricao]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "gerente_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b5a2aeaf-84a6-44fd-8d4d-305dc8108e3d",
            "sourceColumn": "dVendedor[gerente_id]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "lineageTag": "bad14a2f-1818-4f79-b6c8-d11d2a301dd3",
        "partitions": [
          {
            "name": "dgerente",
            "mode": "import",
            "source": {
              "expression": [
                "SUMMARIZE(",
                "    dVendedor,dVendedor[gerente_descricao],dVendedor[gerente_id])"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parâmetro",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b8d01344ade240a7a26b3595ee83d1e9"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "09646b45-0987-4a44-a530-020b8ea3e302",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "65351245-7fb4-482d-bd60-77a831e600c1",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "dd039447-f2eb-4dc1-b6de-d2b4f1b45e98",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "37317bf3-d87c-4a77-acf4-6e5f87937bfb",
        "partitions": [
          {
            "name": "Parâmetro",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Gerente\", NAMEOF('dVendedor'[gerente_descricao]), 0),",
                "    (\"Supervisor\", NAMEOF('dVendedor'[sup_descricao]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ItensVendas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2fccfd05-d35b-41d6-9c69-315b421f362c",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "vendas_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8dd00a0-e191-4c1f-b323-01e0f103b77d",
            "sourceColumn": "vendas_id",
            "summarizeBy": "sum"
          },
          {
            "name": "produto_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "df4b27f0-3d3e-45e0-9c70-a57d901b3aad",
            "sourceColumn": "produto_id",
            "summarizeBy": "sum"
          },
          {
            "name": "item_quantidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c73158c1-e4b6-40fb-9f47-71a6ce70b143",
            "sourceColumn": "item_quantidade",
            "summarizeBy": "sum"
          },
          {
            "name": "valor_unitario",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b0442031-e843-492f-b6b2-194fc50c9350",
            "sourceColumn": "valor_unitario",
            "summarizeBy": "sum"
          },
          {
            "name": "valor_bruto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bcec4e70-f5bd-4e4e-bc9e-b8a348885598",
            "sourceColumn": "valor_bruto",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1dd52ead-22e3-4b8e-ac09-9d9e31a096bd",
        "partitions": [
          {
            "name": "ItensVendas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/Ricardo-Filgueiras/data-experience-week/main/database/ItensVendas.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"id\", Int64.Type}, {\"vendas_id\", Int64.Type}, {\"produto_id\", Int64.Type}, {\"item_quantidade\", Int64.Type}, {\"valor_unitario\", Int64.Type}, {\"valor_bruto\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}